[theme]
# Cor de destaque principal (Amarelo PRF Suave) para botões, checkboxes e focos
primaryColor = "#e4b119"

# Cor de fundo da área principal de conteúdo (Branco/Cinza bem claro)
backgroundColor = "#F1F3F6"

# Cor de fundo da barra lateral (Azul Marinho PRF em baixa tonalidade/pastel)
secondaryBackgroundColor = "#fff"

# Cor principal dos textos da interface
textColor = "#000000"

# Fonte padrão limpa
font = "sans serif"